//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform
    {
        public int PSP_ID { get; set; }
        public string Platform_Desc { get; set; }
        public string Platform_Version { get; set; }
    }
}
