//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProductSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Result_ID { get; set; }

        [Display(Name = "Platform Description")]
        public string PlatformDesc { get; set; }

        [Display(Name = "Exchange")]
        public string ExchCd { get; set; }

        [Display(Name = "Commodity Code")]
        public string ComCD { get; set; }

        [Display(Name = "Contract Description")]
        public string ContractDescription { get; set; }
    }
}
